### ISSUE TITLE
Ensure Pipeline-run references to dataset, problem, and pipeline are valid

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/d3m-experimenter#32]
Related to #8 #29. When inserting a pipeline-run into the database, we need to make sure that the referenced dataset, problem, and pipeline docs are already in the database. If not we should insert them. Without all of these other documents the pipeline-run has little value.

**Comment by orionw** [comment]
We currently have a script that will clean up any afterwords that don't have.  I'll add the checks beforehand as well to prevent future errors.

I'm not sure we should just enter them automatically if they aren't there.  Then we'd have accidental data in there for pipelines that we were perhaps just testing.  Then the db wouldn't have data for that pipeline on every dataset.  If that isn't an issue, I'll add it, but otherwise I'll just not add the pipeline and tell the user to add it to the pipelines first.

**Comment by epeters3** [comment]
Since we are now saving all pipeline runs to the D3M database, the D3M database does those referential integrity checks for us.
